<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HOME" failures="1" tests="4" name="Test" time="52.414" errors="0" timestamp="2025-01-16T20:22:41 IST">
  <testcase classname="teseCases.LoginTestCases" name="verifyFontTypeOfSendButtonInsideResetLink" time="0.145"/>
  <testcase classname="teseCases.LoginTestCases" name="verifyLoginPageWorking" time="2.591"/>
  <testcase classname="teseCases.LoginTestCases" name="verifyTheTextOfResetLinkSendButton" time="1.151">
    <failure type="java.lang.AssertionError" message="Send button inside Reset It link is not working as expected expected [Send] but found [SEND]">
      <![CDATA[java.lang.AssertionError: Send button inside Reset It link is not working as expected expected [Send] but found [SEND]
at teseCases.LoginTestCases.verifyTheTextOfResetLinkSendButton(LoginTestCases.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyTheTextOfResetLinkSendButton -->
  <testcase classname="teseCases.WorkersTestCases" name="verifySelectedValueOfTitleDropDownFromCreateWorkerinWorkerMenu" time="10.297"/>
</testsuite> <!-- Test -->
